name: Fotball Pong Game

on:
  pull-request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      
      - name: Install Poetry
        run: |
          pip install poetry

      - name: Instal Dependencies
        run: |
          poetry install
      
      - name: Test With Flake8
        run: flake8