name: Fotball Pong Game
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Run Image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install project
        run: poetry install
      - name: Test With Flake8git
        run: poetry run flake8
